FROM python:3.14-alpine

LABEL org.opencontainers.image.authors="https://github.com/bunker-pilot"

ENV PYTHONUNBUFFERED=1 \
    UV_PROJECT_ENVIRONMENT=/py

WORKDIR /build

EXPOSE 8000


COPY pyproject.toml uv.lock ./

RUN pip install --no-cache-dir uv && \
    uv sync --frozen --no-dev --no-install-project && \
    rm -rf /tmp/* && mkdir -p /tmp && chmod 1777 /tmp && \
    adduser -D -H django-user

WORKDIR /app


COPY ./app /app


ENV PATH="/py/bin:$PATH"


USER django-user

CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
