# Generated by Django 6.0.7 on 2026-07-28 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_performer_venue_event_seat_ticket_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='reserved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('RESERVED', 'Reserved'), ('PURCHASED', 'Purchased')], default='AVAILABLE', max_length=20),
        ),
    ]
