# Generated by Django 6.0.7 on 2026-07-28 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_ticket_reserved_at_alter_ticket_status'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['status', 'reserved_at'], name='core_ticket_status_391ed6_idx'),
        ),
    ]
