# Generated by Django 6.0.7 on 2026-07-29 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('core', '0004_ticket_core_ticket_status_391ed6_idx'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('ticket',), name='unique_pending_payment_per_ticket'),
        ),
    ]
